### ISSUE TITLE
Text output.

### ISSUE THREAD

**Issue by BlockoS** [BlockoS/HuDK#17]
Add. 
- [x] routines to load a 8x8 font 
- [x] use a plain color (eg not color index #0) for font background :arrow_right: #23 
- [x] text printing routines
- [x] display number in base 10 and 16 :arrow_right: #35
- [x] document:arrow_right: #31
- [x] example(s)

**Comment by BlockoS** [comment]
font loading :white_check_mark:

**Comment by BlockoS** [comment]
:white_check_mark: font printing routines

**Comment by BlockoS** [comment]
Number display in base 10 and 16 :point_right: #35
